version: '3.8'

services:
  starchasers-nginx-config-creator:
    image: starchasers-nginx-config-creator
    volumes:
      - type: volume
        source: backup_vol
        target: /app/persistent
      - "./data:/etc/nginx"
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - CGO_ENABLED=0
      - API_KEY=${API_KEY}

volumes:
  backup_vol:
    driver: local
